services:
  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
      target: test
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - MONGODB_URL=mongodb://mongodb:27017/llm_chat_db_test
    depends_on:
      - mongodb
    networks:
      - app-network
    profiles:
      - test
    # Explicitly run the tests when the container starts
    command: pytest -v

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - app_logs:/var/log/app
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - MONGODB_URL=mongodb://mongodb:27017/llm_chat_db
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
      args:
        - SKIP_TESTS=${SKIP_TESTS:-false}
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://host.docker.internal:8000
      - CHOKIDAR_USEPOLELLING=true
      - SKIP_TESTS=${SKIP_TESTS:-false}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app-network

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: always
    command: ["--noauth"]

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
  app_logs: